### PR TITLE
ft-209 Screen Sharing

### LINKED ISSUE #209: [Feature]: Screenshare
### What feature?

Be able to share a screen.

### LINKED ISSUE #299: [Bug]: Audio visualizer showing when muted/inactive
### Expected Behaviour

Audio visualizer and the audio should not be active when muted or inactivated.

### Actual Behaviour

The audio visualizer is active even when muted.

### How to Reproduce the problem

**ONLY ON [ft-209](https://github.com/Amijakan/mochatto/pull/221)**
After pressing screen share, press mute.

### Additional Info

image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #209 
- Closes #299

## What is within the scope with this PR

- [x] Adding a screen sharing button
- [x] Getting the screen media stream
- [x] Adding a video element within avatar canvas
- [x] Adding a video track to RTCPeerConnection and show the video for all users
- [x] Style

## What is NOT in the scope with this PR

Major UX decisions regarding the screen share feature are not included in this pr

## Other sidenotes that reviewer should be aware of

I haven't extensively tested the behaviors of this feature
If there are any bugs or unexpected behavior, feel free to leave them in the reviews

### CODE REVIEW

**Comment by siberowl** [comment]
**The roadblock**
_tl;dr_
A peer's screen sharing can't be seen. Reproduce by having two users join, and one starting a screen share.

_Details:_
Currently, the local [track](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack) representing audio/video track for a peer user is being updated here:
https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L50

The caller's [ontrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/track_event) fires as expected(?) after the answerer adds an audio track here on entry:
https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L254

However, after adding a video track here (the breakpoint can be reached by starting a screen share for the first time after entry):
https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L263
the caller's ontrack is never fired, thus the local video track is never updated and the peer's screen share can't be seen.

**Comment by siberowl** [comment]
> ### **The roadblock**
> **_tl;dr_** A peer's screen sharing can't be seen. Reproduce by having two users join, and one starting a screen share.
> 
> **_Details:_** Currently, the local [track](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack) representing audio/video track for a peer user is being updated here:
> 
> https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L50
> 
> The caller's [ontrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/track_event) fires as expected (at least I think so?) after the answerer adds an audio track here on entry:
> 
> https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L254
> 
> 
> (It can be tested by putting breakpoints at each location for the caller and answerer respectively.)
> However, after adding a video track here (the breakpoint can be reached by starting a screen share for the first time after entry):
> 
> https://github.com/Amijakan/mochatto/blob/5a7fae8ee81ce8e5a02fe38f9fbc5c540478d5bb/client/src/classes/PeerProcessor.ts#L263
> 
> 
> the caller's ontrack is never fired, **thus the local video track is never updated and the peer's screen share can't be seen.**
> I honestly don't know if I'm understanding ontrack correctly, but looking at examples in the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack), it looks correct

Realized a re-negotiation is needed after calling navigator.getUserMedia
https://stackoverflow.com/questions/66493707/webrtc-addtrack-addstream-after-createoffer

**Comment by siberowl** [comment]
Todo:
- [ ] append the video element to the AvatarDOM once the peer avatar is created, and style it
- [ ] Hide the video element once the stream ends (when a user stops sharing) and unhide on start

**Comment by Njima1572** [comment]
SUCCESS

**Comment by siberowl** [comment]
image
Currently looks like this

**Comment by Njima1572** [comment]
You can also update README and check screen sharing section.

File: client/src/classes/PeerProcessor.ts [hunk 1]
```diff
@@ -181,48 +202,86 @@ export class PeerProcessor {
...
+        }
+        // add the track
+        this.peerStream.addTrack(track);
 
-    // set the new stream as the audio source and play
-    this.player.srcObject = this.stream;
-    this.player.play();
-    this.player.autoplay = true;
+        // If video player doesn't exist, create.
+        this.videoPlayer ??= document.createElement("video");
```
Comment (Njima1572) [inline client/src/classes/PeerProcessor.ts:253]: I've never seen `??=` before. seems pretty handy.

File: client/src/classes/PeerProcessor.ts [hunk 2]
```diff
@@ -12,28 +12,34 @@ export class PeerProcessor {
   peerConnection: RTCPeerConnection;
   dataChannel: RTCDataChannel;
   socket: Socket;
-  sender: RTCRtpSender;
+  audioSender: RTCRtpSender;
+  videoSender: RTCRtpSender;
```
Comment (Njima1572) [inline client/src/classes/PeerProcessor.ts:16]: Not sure if we will ever implement video from camera, but if so, can the new video stream be added to this same `videoSender`?

File: client/src/classes/PeerProcessor.ts [hunk 3]
```diff
@@ -168,7 +189,7 @@ export class PeerProcessor {
   getVolume(selfPosition: [number, number], peerPosition: [number, number]): number {
     const distance = Math.sqrt(
       Math.pow(selfPosition[0] - peerPosition[0], 2) +
-      Math.pow(selfPosition[1] - peerPosition[1], 2)
+        Math.pow(selfPosition[1] - peerPosition[1], 2)
```
Comment (Njima1572) [inline client/src/classes/PeerProcessor.ts:192]: For later refactoring, this can be part of the `utils.ts`

File: client/src/components/ScreenShareWindow.tsx [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+        stream.getVideoTracks()[0].onended = () => {
+          onEnd();
+        };
+      })
+      .catch((e) => {
+        onFailed(e);
+      });
+  }, []);
+
+  return <></>;
```
Comment (Njima1572) [inline client/src/components/ScreenShareWindow.tsx:26]: It seems like `ScreenShareWindow` is not really a `window` and I don't think this is intuitive.
If getDisplayMedia is the only thing it is doing, I dont think this needs to be React component. More like a function that gets called when user clicks on shareScreenButton.

File: client/src/components/ScreenShareWindow.tsx [hunk 5]
```diff
@@ -0,0 +1,29 @@
+import React, { useEffect, useState, useRef } from "react";
```
Comment (Njima1572) [inline client/src/components/ScreenShareWindow.tsx:1]: unused `useState` and `useRef`

**Review by Njima1572 — CHANGES_REQUESTED** [review]

File: client/src/classes/PeerProcessor.ts (hunk 2 above)
Comment (siberowl) [reply client/src/classes/PeerProcessor.ts:16]: I think if there's a new video stream, I should be able to just take the track and add it to the current video stream?
I'm actually not even sure if I need separate logic for video and audio...??? hmmmm

File: client/src/classes/PeerProcessor.ts (hunk 3 above)
Comment (siberowl) [reply client/src/classes/PeerProcessor.ts:192]: I agree

Comment (siberowl) [reply client/src/classes/PeerProcessor.ts:192]: - #251

File: client/src/components/ScreenShareWindow.tsx (hunk 4 above)
Comment (siberowl) [reply client/src/components/ScreenShareWindow.tsx:26]: True true I agree. The component kind of diverted from my original idea so I'll try renaming it/refactoring it a bit.

File: client/package.json [hunk 6]
```diff
@@ -64,7 +64,7 @@
     "eslint-plugin-react-hooks": "^4.2.0",
     "sass": "^1.52.1",
     "serve": "^12.0.1",
-    "typescript": "^4.1.2",
+    "typescript": "^4.7.2",
```
Comment (siberowl) [inline client/package.json:67]: Needed to update in order to include .getDisplayMedia() in the typescript definitions

File: client/src/classes/PeerProcessor.ts [hunk 7]
```diff
@@ -133,6 +141,19 @@ export class PeerProcessor {
   onDataChannelMessage(event: MessageEvent): void {
     const info = JSON.parse(event.data);
     this.addUserInfo(info);
+    if (info.isScreenSharing) {
+      if (!this.screenShareTrigger) {
+        this.screenShareTrigger = true;
+        // If video player doesn't exist, create.
+        this.videoPlayer ??= document.createElement("video");
+        document.getElementById("avatar-video-" + this.peerId)?.appendChild(this.videoPlayer);
```
Comment (CaseRegan) [inline client/src/classes/PeerProcessor.ts:149]: Imo there should be a way to get the user object by id and then call something like `userInfo.byId(this.peerId).addVideo(videoPlayer: HTMLVideoElement)`. Adding stuff to the dom shouldn't be the responsibility of the peerprocessor

File: client/src/pages/RoomPage/index.tsx [hunk 8]
```diff
@@ -97,6 +108,30 @@ function RoomPage({ name }: { name: string }): JSX.Element {
...
 
+  const onStartScreenSharing = (_stream: MediaStream) => {
+    const videoPlayer = document.createElement("video");
+    const screenShareTrack = _stream.getVideoTracks()[0];
+    const mixedStream = stream.clone();
+
+    // Set video player configurations and append to self avatar
+    videoPlayer.srcObject = _stream;
+    videoPlayer.autoplay = true;
+    document.getElementById("avatar-video-" + socket.id)?.appendChild(videoPlayer);
```
Comment (CaseRegan) [inline client/src/pages/RoomPage/index.tsx:119]: Same as comment in peerprocessor

File: client/src/classes/PeerProcessor.ts (hunk 7 above)
Comment (siberowl) [reply client/src/classes/PeerProcessor.ts:149]: I totally agree.
I thought about this a little bit but in order to do this, "userInfo" needs to be an actual class instead of just an object and changing this would be way out of the scope for the pr imo.
Also, while I'm at it, I think it would be better to refactor this whole part so that we have a NetworkContext which holds User instances such that it can be used like:
* network.getUsers()
* network.getUserById(id).addVideoPlayer(videoPlayer)
* network.getUsers()[0].name
* network.getUsers()[0].peerProcessor

Comment (siberowl) [reply client/src/classes/PeerProcessor.ts:149]: So I'm thinking I'll just do all of that refactoring in a different issue.

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by siberowl** [comment]
Some refactors broke it. Currently fixing it.

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

File: client/src/pages/RoomPage/index.tsx [hunk 9]
```diff
@@ -210,7 +210,7 @@ function RoomPage({ name }: { name: string }): JSX.Element {
       stream.getAudioTracks()[0].enabled = !selfUserInfoRef.current.mute;
     }
     networkRef.current?.updateInfo(selfUserInfoRef.current);
-  }, [selfUserInfoRef.current]);
+  }, [selfUserInfoRef.current.mute, stream]);
```
Comment (siberowl) [inline client/src/pages/RoomPage/index.tsx:213]: This is being used to update all info not just mute so this dependency is incorrect.

Comment (siberowl) [reply client/src/pages/RoomPage/index.tsx:213]: It's probably better to split each hook for readability

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

File: client/src/pages/RoomPage/index.tsx [hunk 10]
```diff
@@ -210,7 +210,7 @@ function RoomPage({ name }: { name: string }): JSX.Element {
       stream.getAudioTracks()[0].enabled = !selfUserInfoRef.current.mute;
     }
     networkRef.current?.updateInfo(selfUserInfoRef.current);
-  }, [selfUserInfoRef.current.mute, stream]);
+  }, [selfUserInfoRef.current, stream]);
```
Comment (siberowl) [inline client/src/pages/RoomPage/index.tsx:213]: The stream is unneeded too since then, the avatar position won't be updated on mute.

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-221.dev.mochatto.com

**Review by Njima1572 — APPROVED** [review]
LGTM (Great work
