### PR TITLE
bg-217 properly closing streams

### LINKED ISSUE #217: [Bug]: Grey avatar remains after user leaves
### Expected Behaviour

The avatar should disappear when the user leaves.
Re-occurrence of: #175

### Actual Behaviour

A grey avatar spawns at the default location after a user leaves.

### How to Reproduce the problem

Currently no way to reproduce it consistently. Will add more details later.

### Additional Info

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #217 

## What is within the scope with this PR

Fixing the bug.

Since the data streams were not being closed after a user left, on some occasions, there were still "left over" data which ended up calling addUserInfo(), re-adding the deleted user avatar.
I fixed the bug by properly closing the streams after a user leaves.

### CODE REVIEW

File: client/src/pages/RoomPage.tsx [hunk 1]
```diff
@@ -71,9 +76,14 @@ function RoomPage({ name }: { name: string }): JSX.Element {
     setShowNotification(true);
   };
 
+  // When a user leaves.
   const onLeave = (id: string) => {
-    setAnnouncement(globalUserInfos[id].name + " has left.");
+    // Find the peer processor within the network and close the streams.
+    networkRef.current.findPeerProcessorById(id).close();
```
Comment (siberowl) [inline client/src/pages/RoomPage.tsx:82]: Calling close() here to end the streams.

**Comment by Njima1572** [comment]
Do we need to keep the `network` state??

File: client/src/pages/RoomPage.tsx [hunk 2]
```diff
@@ -34,8 +34,8 @@ function RoomPage({ name }: { name: string }): JSX.Element {
   const { userInfos, addUserInfo, removeUserInfo } = useContext(UserInfoContext);
   const history = useHistory();
   const [showModal, setShowModal] = useState(false);
-
   const [network, setNetwork] = useState<Network>(null as unknown as Network);
```
Comment (Njima1572) [inline client/src/pages/RoomPage.tsx:37]: Seems like `network` state can be removed

File: client/src/pages/RoomPage.tsx [hunk 3]
```diff
@@ -52,6 +52,11 @@ function RoomPage({ name }: { name: string }): JSX.Element {
     setVisualizer(_visualizer);
   };
 
+  const updateNetwork = (_network) => {
+    networkRef.current = _network;
+    setNetwork(_network);
```
Comment (Njima1572) [inline client/src/pages/RoomPage.tsx:57]:
```suggestion
```

File: client/src/pages/RoomPage.tsx [hunk 4]
```diff
@@ -52,6 +52,11 @@ function RoomPage({ name }: { name: string }): JSX.Element {
...
+  };
+
```
Comment (Njima1572) [inline client/src/pages/RoomPage.tsx:59]:
```suggestion
```

File: client/src/pages/RoomPage.tsx [hunk 5]
```diff
@@ -85,7 +95,7 @@ function RoomPage({ name }: { name: string }): JSX.Element {
 
   // open all listeners on render
   useEffect(() => {
-    setNetwork(new Network(socket, name, addUserInfo, selfUserInfoRef.current, stream));
+    updateNetwork(new Network(socket, name, addUserInfo, selfUserInfoRef.current, stream));
```
Comment (Njima1572) [inline client/src/pages/RoomPage.tsx:98]:
```suggestion
    networkRef.current = new Network(socket, name, addUserInfo, selfUserInfoRef.current, stream);
```

**Review by Njima1572 — COMMENTED** [review]
updateNetwork function can be kept for more intuitive naming, but `network` state seemed extra

File: client/src/pages/RoomPage.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (siberowl) [reply client/src/pages/RoomPage.tsx:37]: Since the reference depends on useState, the state is still needed.
See: https://stackoverflow.com/questions/62806541/how-to-solve-the-react-hook-closure-issue

[the remark this answers is not in the document]
Comment (Njima1572) [reply client/src/pages/RoomPage.tsx:37]: It doesn't seem like it needs to be a "state" of the component, since setState, which causes re-rendering is only called in useEffect. (It seem to work without the "state" network if you try it)

**Review by Njima1572 — APPROVED** [review]
LGTM!
