### PR TITLE
rf-274-patch Fixed white screen on user entry bug

### LINKED ISSUE #281: [Bug]: White screen on user entry
### Expected Behaviour

No blank screen on entry.

### Actual Behaviour

Nothing is displayed on user entry.

### How to Reproduce the problem

Enter a room as a user, and enter the same user as another user.

### Additional Info

image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #281

## What is within the scope with this PR

Fixing bug.

### CODE REVIEW

File: client/src/components/AvatarCanvas/AvatarDOM/index.tsx [hunk 1]
```diff
@@ -75,11 +75,11 @@ const areEqual = (prev, next) => {
     prev._borderColor === next._borderColor &&
     prev.pos[0] === next.pos[0] &&
     prev.pos[1] === next.pos[1] &&
-    prev.initial[1] === next.initial[1] &&
+    prev.initial === next.initial &&
```
Comment (siberowl) [inline client/src/components/AvatarCanvas/AvatarDOM/index.tsx:78]: Since the initial is a single character string, there is no 2nd index.

**Review by Njima1572 — APPROVED** [review]
LGTM! Thank you for catching it!
