### PR TITLE
bg-370 Fixed stale analyzer bug

### LINKED ISSUE #370: [Bug]: Changing audio device doesn't work
### Expected Behaviour

Changing audio device will properly change the audio device without retaining the old track.

### Actual Behaviour

Seems like the newly selected stream retains the old audio track.

### How to Reproduce the problem

Go on join page or room page, select a device with audio and check that the visualizer is working. Then select an audio device without audio and see that the visualizer is still picking up audio.

### Additional Info

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #370

## What is within the scope with this PR

The audio visualizer was broken because the draw function was using stale variables outside of its closure. Fixed it by placing it in the root of the class.

## Testing guidance

Switch between audio sources with different volume outputs in the join page and room page to make sure that everything is working.

PRVM: https://bg-370.dev.mochatto.com/

### CODE REVIEW

File: client/src/classes/AudioVisualizer.ts [hunk 1]
```diff
@@ -25,24 +31,24 @@ export class AudioVisualizer {
...
-        // Update previous average once current average meets threshold
-        prevAverage = average;
-      }
-      window.requestAnimationFrame(draw);
-    };
-    draw();
+    this.animationFrameId = window.requestAnimationFrame(this.draw(analyser, 0));
   }
+
+  draw = (analyser: AnalyserNode, prevAverage: number) => (_step: number) => {
```
Comment (siberowl) [inline client/src/classes/AudioVisualizer.ts:38]: Took the draw out of the `setStream` function and placed it at the root of the class to avoid a stale closure.

**Review by Njima1572 — APPROVED** [review]
Seems to resolve the bug, LGTM!
