### PR TITLE
Ft 347 disable phone from sleeping

### LINKED ISSUE #347: [Bug]: disable phone sleeping when room page is open
### Expected Behaviour

Chat should keep working when user is in a room.

### Actual Behaviour

The phone will go to sleep after a while which makes the user either disconnect from the room or get muted depending on the environment.

### How to Reproduce the problem

_No response_

### Additional Info

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #347 

## What is within the scope with this PR
- Adding Toggle component
- Adding no sleep functionality in mobile

### CODE REVIEW

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

File: client/src/components/AutoSleepToggle/index.tsx [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import React, { useEffect } from 'react'
+import NoSleep from 'nosleep.js'
+import { isMobile } from '@/utils'
+import { Toggle } from "@/components";
+import './style.scss'
+
+const AutoSleepToggle = ({ noSleepEnabled, setNoSleepEnabled }: { noSleepEnabled: boolean, setNoSleepEnabled: (arg0: boolean) => void }): JSX.Element => {
```
Comment (siberowl) [inline client/src/components/AutoSleepToggle/index.tsx:7]: I think we should change these props (`noSleepEnabled, setNoSleepEnabled`) to something more intuitive.

File: client/src/components/AutoSleepToggle/index.tsx [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  const noSleep = new NoSleep()
+
+  useEffect(() => {
+    if (isMobile) {
+      noSleepEnabled ? noSleep.enable() : noSleep.disable()
+    }
+  }, [noSleepEnabled])
+
+  return isMobile ? (
```
Comment (siberowl) [inline client/src/components/AutoSleepToggle/index.tsx:16]: The check for isMobile might need to be in the RoomPage since rn, the divider shows up even on the desktop which looks weird.
image

File: client/src/components/Toggle/index.tsx [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+import './style.scss'
+
+const Toggle = ({ selected, setSelected, disabled = false }: { selected: boolean, setSelected: (arg0: boolean) => void, disabled?: boolean }): JSX.Element => {
+
+  const handleToggle = () => {
+    if (!disabled) setSelected(!selected)
+  }
+
+  const dataAttributes = {
+    'data-selected': selected ? 'on' : 'off',
```
Comment (siberowl) [inline client/src/components/Toggle/index.tsx:11]: These look nifty. I should start using them more 👍

**Review by siberowl — COMMENTED** [review]
Mostly looks good, just a few comments. Awesome work!✔️

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-352.dev.mochatto.com

**Review by siberowl — APPROVED** [review]
LGTM!
