### PR TITLE
bg-225 defaulting to invisible and setting display to none prerender

### LINKED ISSUE #225: [Bug]: Set default avatar color to invisible
### Expected Behaviour

The default avatar color during a bug should be invisible.

### Actual Behaviour

The default color is grey.

### How to Reproduce the problem

1. Set a breakpoint at `const background = getColor(random, 1, 1);` in `AvatarCanvas.tsx`
2. Join a room

### Additional Info

image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #225 

## What is within the scope with this PR

Changing default color to be invisible and setting display to none preload.

## Other sidenotes that reviewer should be aware of

You can compare the behavior with main by setting a breakpoint at `setIsRendered(true);` (line 40) in `AvatarDOM.tsx` and joining a room.

### CODE REVIEW

File: client/src/components/AvatarDOM.tsx [hunk 1]
```diff
@@ -56,16 +58,12 @@ function AvatarDOM({
 
   return (
     <div
-      className={cx("avatar", "avatar-outer")}
+      className={cx("avatar", "avatar-outer", { "no-show": !isRendered })}
```
Comment (Njima1572) [inline client/src/components/AvatarDOM.tsx:61]: I like this

**Review by Njima1572 — APPROVED** [review]
LGTM

File: client/src/components/AvatarDOM.tsx (hunk 1 above)
Comment (siberowl) [reply client/src/components/AvatarDOM.tsx:61]: Wakaru
